### ISSUE TITLE
Allow not specifying master ResourceMapping

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#66]
- mainly because we just want to use the inner mapping

**Comment by masayag** [comment]
It should already be supported within the existing code:

https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L414

If the external mapping resource ID wasn't provided, we should proceed with the internal mapping:
https://github.com/kubevirt/vm-import-operator/blob/f097f3b3d33bae2769194c49c98ec47db06db366/pkg/providers/ovirt/mappings/merger.go#L9

Did you encounter a failure with that ?

**Comment by atiratree** [comment]
I am getting this with recent ondra's image

```yaml
apiVersion: v1
items:
- apiVersion: v2v.kubevirt.io/v1alpha1
  kind: VirtualMachineImport
  metadata:
    creationTimestamp: "2020-04-09T14:54:01Z"
    generateName: vm-import-myvm-
    generation: 1
    name: vm-import-myvm-lzx27
    namespace: default
    resourceVersion: "472710"
    selfLink: /apis/v2v.kubevirt.io/v1alpha1/namespaces/default/virtualmachineimports/vm-import-myvm-lzx27
    uid: 60c1800a-034d-48e8-a280-f60d2c5b6872
  spec:
    providerCredentialsSecret:
      name: admin-10-37-140-88-rhev-lab-en-zlp6f
      namespace: default
    source:
      ovirt:
        diskMappings:
        - source:
            id: 64302e7f-3f08-4d32-9fe1-59b6c383acb5
          target:
            name: local
        networkMappings: []
        storageMappings: []
        vm:
          id: c1a784d6-4747-4c26-8b47-d3d6766436e1
    startVM: false
    targetVmName: myvm
  status:
    conditions:
    - lastHeartbeatTime: "2020-04-09T14:54:56Z"
      lastTransitionTime: "2020-04-09T14:54:03Z"
      message: Storage and Disk mappings are missing
      reason: IncompleteMappingRules
      status: "False"
      type: Validating
    - lastHeartbeatTime: "2020-04-09T14:54:56Z"
      lastTransitionTime: "2020-04-09T14:54:03Z"
      message: 'VM specifies IO Threads: 0, VM has NUMA tune mode secified: interleave'
      reason: MappingRulesCheckingReportedWarnings
      status: "True"
      type: MappingRulesChecking
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```

**Comment by jakub-dzon** [comment]
I tried to reproduce the problem with:
```yaml
apiVersion: v2v.kubevirt.io/v1alpha1
kind: VirtualMachineImport
metadata:
  name: vm-import-myvm-lzx27
  namespace: default
spec:
  providerCredentialsSecret:
    name: ovirt-credentials
    namespace: default
  source:
    ovirt:
      mappings:
        diskMappings:
          - source:
              id: 95cb7ca2-186b-4367-9ff3-5a9cf566e48d
            target:
              name: hostpath
        networkMappings: []
        storageMappings: []
      vm:
        id: 2333e36d-2a83-425d-861a-d2b53eb77697
  startVM: false
  targetVmName: myvm
```
and there were no validation errors.
The VM had one disk and no NICs. When it had NIC, the validation failure was different and as expected.

I pushed the image from code that worked that way for me: `quay.io/jdzon/vm-import-operator:v0.0.1`; can you try with it?

**Comment by atiratree** [comment]
Tried the image and still the same

### Pod: vm-import-operator-86569765f8-zzd5b

spec:
```
...
      imagePullPolicy: Always
      image: 'quay.io/jdzon/vm-import-operator:v0.0.1'
...
```

log:

``` json
{"level":"info","ts":1586856008.1997097,"logger":"controller_virtualmachineimport","msg":"Reconciling VirtualMachineImport","Request.Namespace":"default","Request.Name":"vm-import-cirrosvm-xbd4d"}
{"level":"info","ts":1586856009.3082345,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.cpu_shares VM specifies CPU shares that should be available to it}"}
{"level":"info","ts":1586856009.3083558,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.display.type VM uses spice display}"}
{"level":"info","ts":1586856009.3084097,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.high_availability.priority VM uses high availability priority: 1}"}
{"level":"info","ts":1586856009.3084412,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.memory_policy.guaranteed VM specifies guaranteed memory: 536870912}"}
{"level":"info","ts":1586856009.3084838,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.migration VM has migration options specified}"}
{"level":"info","ts":1586856009.3085396,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.migration_downtime VM has migration downtime specified: -1}"}
{"level":"info","ts":1586856009.3086166,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.storage_error_resume_behaviour VM has storage error resume behaviour set: auto_resume}"}
{"level":"info","ts":1586856009.3086553,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.graphic_consoles.protocol VM has non-VNC graphics console configured: spice}"}
{"level":"info","ts":1586856009.308682,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {vm.quota VM has quota with ID fb7f8f0e-22f4-47a2-95ba-441efa23cebb assigned}"}
{"level":"info","ts":1586856009.3087177,"logger":"validation","msg":"Validation information for default/vm-import-cirrosvm-xbd4d: {disk_attachment.disk.propagate_errors disk 64302e7f-3f08-4d32-9fe1-59b6c383acb5 has propagate_errors configured: false}"}
{"level":"info","ts":1586856009.314242,"logger":"controller_virtualmachineimport","msg":"Import blocked. Storage and Disk mappings are missing","Request.Namespace":"default","Request.Name":"vm-import-cirrosvm-xbd4d"}
```

### VMImport: vm-import-cirrosvm-xbd4d

``` yaml
apiVersion: v1
items:
- apiVersion: v2v.kubevirt.io/v1alpha1
  kind: VirtualMachineImport
  metadata:
    creationTimestamp: "2020-04-14T09:19:47Z"
    generateName: vm-import-cirrosvm-
    generation: 1
    name: vm-import-cirrosvm-xbd4d
    namespace: default
    resourceVersion: "485203"
    selfLink: /apis/v2v.kubevirt.io/v1alpha1/namespaces/default/virtualmachineimports/vm-import-cirrosvm-xbd4d
    uid: 4e86f28a-1f07-41dc-a94e-1151348db0b3
  spec:
    providerCredentialsSecret:
      name: admin-10-37-140-88-rhev-lab-en-lnxst
      namespace: default
    source:
      ovirt:
        diskMappings:
        - source:
            id: 64302e7f-3f08-4d32-9fe1-59b6c383acb5
          target:
            name: local
        networkMappings: []
        storageMappings: []
        vm:
          id: c1a784d6-4747-4c26-8b47-d3d6766436e1
    startVM: false
    targetVmName: cirrosvm
  status:
    conditions:
    - lastHeartbeatTime: "2020-04-14T09:24:46Z"
      lastTransitionTime: "2020-04-14T09:19:49Z"
      message: Storage and Disk mappings are missing
      reason: IncompleteMappingRules
      status: "False"
      type: Validating
    - lastHeartbeatTime: "2020-04-14T09:24:46Z"
      lastTransitionTime: "2020-04-14T09:19:49Z"
      message: 'VM specifies IO Threads: 0, VM has NUMA tune mode secified: interleave'
      reason: MappingRulesCheckingReportedWarnings
      status: "True"
      type: MappingRulesChecking
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by jakub-dzon** [comment]
I was able to reproduce the error and I'll investigate.

**Comment by jakub-dzon** [comment]
The import yaml is not in the required schema; mappings should be located under `spec.source.ovirt.mappings`, not `spec.source.ovirt`:
```yaml
  source:
    ovirt:
      mappings:
        diskMappings:
          - source:
              id: 64302e7f-3f08-4d32-9fe1-59b6c383acb5
            target:
              name: local
        networkMappings: []
        storageMappings: []
```

**Comment by atiratree** [comment]
ah sorry, works!

I also get this if I do not specify SC (not sure if your PR fixes that):

```yaml
    source:
      ovirt:
        mappings:
          diskMappings:
          - source:
              id: 64302e7f-3f08-4d32-9fe1-59b6c383acb5
            target:
              name: null
          networkMappings: []
          storageMappings: []
        vm:
          id: c1a784d6-4747-4c26-8b47-d3d6766436e1
    startVM: false
    targetVmName: cirrosvm
  status:
    conditions:
    - lastHeartbeatTime: "2020-04-14T12:03:43Z"
      lastTransitionTime: "2020-04-14T12:03:08Z"
      message: 'Storage class  has not been found for disk 64302e7f-3f08-4d32-9fe1-59b6c383acb5.
        Error: StorageClass.storage.k8s.io "" not found'
      reason: IncompleteMappingRules
      status: "False"
      type: Validating
    - lastHeartbeatTime: "2020-04-14T12:03:43Z"
      lastTransitionTime: "2020-04-14T12:03:08Z"
      message: 'VM specifies IO Threads: 0, VM has NUMA tune mode secified: interleave'
      reason: MappingRulesCheckingReportedWarnings
      status: "True"
      type: MappingRulesChecking
kind: List
```

**Comment by atiratree** [comment]
btw shouldn't we allow not specifying mappings as it should resolve to null / default SCs?

I guess they are required only when the VM has NICs

**Comment by jakub-dzon** [comment]
PR #81 for issue #65 allows for that.

**Comment by jakub-dzon** [comment]
I don't think we should allow user to specify lack of mapping by providing null storage class name.

**Comment by atiratree** [comment]
default SC is quite a standard in k8s

I guess it is not such a big issue as they will probably have to use nic mapping anyway

**Comment by jakub-dzon** [comment]
Well - they will be able to skip the storage mapping completely; just specifying null seems odd.

**Comment by atiratree** [comment]
> Well - they will be able to skip the storage mapping completely; just specifying null seems odd.

+1, I just meant possibility of skipping `ovirt.mappings` as I had in my buggy example

**Comment by jakub-dzon** [comment]
@suomiy - the other PR has been merged and I've pushed quay.io/jdzon/vm-import-operator:v0.0.3   with these changes.

**Comment by jakub-dzon** [comment]
@suomiy - can this issue be closed?

**Comment by atiratree** [comment]
yup, works ok now
